[phases.setup]
nixPkgs = ['php81', 'mysql', 'nodejs_18']

[phases.install]
cmds = [
  # Instala o Composer manualmente
  'curl -sS https://getcomposer.org/installer | php',
  'mv composer.phar /usr/local/bin/composer',
  
  # Instala as dependências do Laravel
  'composer install --no-interaction --prefer-dist --optimize-autoloader',
  'npm ci',
  'php artisan key:generate',
  'php artisan migrate --force'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
