[phases.setup]
nixPkgs = ['php81', 'mariadb', 'nodejs_18', 'curl']

[phases.install]
cmds = [
  # Baixa e instala o Composer
  'curl -sS https://getcomposer.org/installer | php',
  'chmod +x composer.phar',
  'mv composer.phar /usr/local/bin/composer',

  # Verifica se o Composer está disponível
  'composer --version',

  # Instala dependências Laravel
  'composer install --no-interaction --prefer-dist --optimize-autoloader',
  'npm ci',
  'php artisan key:generate',
  'php artisan migrate --force'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
