[phases.setup]
nixPkgs = ['php81', 'mariadb', 'nodejs_18', 'curl']

[phases.install]
cmds = [
  '''
  # Instala o Composer em um único comando
  curl -sS https://getcomposer.org/installer | php &&
  chmod +x composer.phar &&
  mv composer.phar /usr/local/bin/composer &&
  composer --version &&

  # Instala dependências do Laravel
  composer install --no-interaction --prefer-dist --optimize-autoloader &&
  npm ci &&
  php artisan key:generate &&
  php artisan migrate --force
  '''
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
